### ISSUE TITLE
mulitiple delete

### ISSUE THREAD

**Issue by jazzy1986** [daveismyname/pdo-wrapper#10]
your wrapper are amazing, clean & simple, save me a lot of time.
will you gonna add multiple delete method? 
currently i use raw method to delete record with different id.
my code as below.

 $ids = implode("','",$_POST['ids']); 
 $db->raw("delete from '.$table.' where cm_id in('".$ids."')");
 echo json_encode($ids);

**Comment by daveismyname** [comment]
I've added a new method for this now under a new release, you'll have to update or manually add the method.

To delete multiple records where ids are in a specific column, this uses WHERE id IN (4,5,6)

```php
$db->deleteByIds('users', 'id', '4,5,6');
```
