### ISSUE TITLE
Missing attribute to get the rowCount value when using update

### ISSUE THREAD

**Issue by terrybr** [daveismyname/pdo-wrapper#3]
I just found this little but so useful PDO wrapper.  However, the rowCount was always returning 0 when I was using the $db->update method.

I fixed changing line 46 to:

 $instance = new Database("$type:host=$host;dbname=$name;charset=utf8", $user, $pass, array(PDO::MYSQL_ATTR_FOUND_ROWS => true));

Cheers!

**Comment by LegitSoulja** [comment]
@terrybr check out https://github.com/ThreeLetters/SuperSQL/
