### ISSUE TITLE
feature sugestion: count method

### ISSUE THREAD

**Issue by ezetojo** [daveismyname/pdo-wrapper#4]
count method.

$db->count("dbname");

**Comment by ezetojo** [comment]
```
/**
* Count method
* @param  string $table table name
*/
public function count($table){
  $stmt = $this->prepare("SELECT id FROM $table");
  $stmt->execute();
  return $stmt->rowCount();
}
```

is that ok? i made it based on your methods.

**Comment by daveismyname** [comment]
Yes looks good, I'll accept if you open a PR so you get credit for this.

**Comment by daveismyname** [comment]
I've added this now. https://github.com/daveismyname/pdo-wrapper/commit/bd162fb7c98d404a6a45d81b1dec69f3b095e1d8
